server:
  port: 8080
spring:
  application:
    name: ect888
#配置信息
amc:
  ect:
    #证通下发的公钥
    publicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCCIjEFl2tn3W9GssK0iDju2ILU5UlLwinOEy7CiZAF9Q/gYXPoAr8AWx3gQ8UVAszAEw1X25Qa2TPq63/boiLip6299pbzpCAToFFHzNhZT6SFm0HDvOQWJxs8k/kUDDMRF+TUbf9NJekhtg87bbMAB68fi3/jreeYJ7OYC5ZKSwIDAQAB
    #华夏设定的密码
    newPtyPwd: hxods2020
    #华夏设定的密钥
    ptyKey: bjsyhxjjkfxthxods2020
    #证通下发的机构账号
    ptyacct: hxfundacct01
    #证通下发的机构号
    ptycd: 0103400008
    #访问证通接口地址
    url: https://112.65.144.19:9085/servlet/json

#httpclien配置信息
http:
  config:
    #最大线程数
    maxTotal: 250
    #每个网络路由的最大数
    defaultMaxPerRoute: 200
    #尝试关闭空闲网络连接的时间间隔，单位秒
    closeIdleConnections: 30
    #是否启动代理
    proxy: false