server:
  port: 10000
spring:
  application:
    name: gateway-sentinel-example
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: nacos-example  #路由的id，没有固定规则但是要求唯一，建议配合服务名
          uri: lb://nacos-example/   #匹配后提供服务的路由地址
          #uri: http://127.0.0.1:8001/  #匹配后提供服务的路由地址
          predicates:
            - Path=/nacos/**   #断言，路径相匹配进行路由
      httpclient:
        response-timeout: 3000  #网关响应超时时间
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 #nacos作为服务注册的地址
      config:
        server-addr: 127.0.0.1:8848 #nacos作为配置中心的地址
        file-extension: yaml #执行yaml格式的配置
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080
# 暴露端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always